/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.3.10
 * on Fri Jan 13 12:44:23 CET 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Swc_Input.h>
#include "Pwm.h"

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) Swc_Input_Runnable_Logic_Swc_Input (void)
{
  boolean arg_IWrite_data = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef;
  uint8 arg_IWrite_data_0 = 0U;
  P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_0;
  boolean arg_IWrite_data_1 = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_1;
  boolean arg_IWrite_data_2 = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_2;
  boolean arg_IWrite_data_3 = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_3;
  boolean ret_IRead;
  boolean ret_IRead_0;
  boolean ret_IRead_1;
  boolean ret_IRead_2;
  boolean ret_IRead_3;
  
  //User defined vars 
  static uint16 redValue = 0;
  static uint16 greenValue = 0x1000;
  static uint16 blueValue = 0x8000 - 0x1000;
  


  ret_IRead = Rte_IRead_Runnable_Logic_Swc_Input_R_IO_Button_sw2_value();  
  ret_IRead_0 = Rte_IRead_Runnable_Logic_Swc_Input_R_IO_Button_sw3_value();
  
  //ret_IRead_1 = Rte_IRead_Runnable_Logic_Swc_Input_R_Button_test_value();
  ret_IRead_2 = Rte_IRead_Runnable_Logic_Swc_Input_R_IO_Button_sw7_value();
  ret_IRead_3 = Rte_IRead_Runnable_Logic_Swc_Input_R_IO_Button_sw8_value();

if (ret_IRead == 1)
	{
		redValue = (redValue + 0x500) % 32768; 
		greenValue = (greenValue + 0x1000) % 32768; 
		blueValue = (blueValue + 0x500) % 32768; 
		
		Pwm_SetDutyCycle(PwmChannel_0_RED, redValue);
		Pwm_SetDutyCycle(PwmChannel_1_GREEN, greenValue);
		Pwm_SetDutyCycle(PwmChannel_2_BLUE, blueValue); 	
	}
	
	else
	{
		Pwm_SetDutyCycle(PwmChannel_2_BLUE, 0x0000);   
	}

if (ret_IRead_0 == 1) { 
		Pwm_SetDutyCycle(PwmChannel_0_RED, 0x1000);

		} else {
		Pwm_SetDutyCycle(PwmChannel_0_RED, 0x0000);
		}

if (ret_IRead_2 == 1) { 
		Pwm_SetDutyCycle(PwmChannel_1_GREEN, 0x1000);

		} else {
		Pwm_SetDutyCycle(PwmChannel_1_GREEN, 0x0000);
		}
		
if (ret_IRead_3 == 1) { 
		Pwm_SetDutyCycle(PwmChannel_0_RED, 0x1000);
		Pwm_SetDutyCycle(PwmChannel_2_BLUE, 0x1000);

		} else {
		Pwm_SetDutyCycle(PwmChannel_0_RED, 0x0000);
		Pwm_SetDutyCycle(PwmChannel_2_BLUE, 0x0000);
		}


  Rte_IWrite_Runnable_Logic_Swc_Input_P_Button_sw2_value(ret_IRead);
  ret_IWriteRef = Rte_IWriteRef_Runnable_Logic_Swc_Input_P_Button_sw2_value();
  
  Rte_IWrite_Runnable_Logic_Swc_Input_P_Button_sw3_value(ret_IRead_0);
  ret_IWriteRef_3 = Rte_IWriteRef_Runnable_Logic_Swc_Input_P_Button_sw3_value();
  
  Rte_IWrite_Runnable_Logic_Swc_Input_P_Button_sw7_value(ret_IRead_2);
  ret_IWriteRef_1 = Rte_IWriteRef_Runnable_Logic_Swc_Input_P_Button_sw7_value();
  
  Rte_IWrite_Runnable_Logic_Swc_Input_P_Button_sw8_value(ret_IRead_3);
  ret_IWriteRef_2 = Rte_IWriteRef_Runnable_Logic_Swc_Input_P_Button_sw8_value();
  
  
  /*
  Rte_IWrite_Runnable_Logic_Swc_Input_P_Swc_Input_status_value(arg_IWrite_data_0);
  ret_IWriteRef_0 = Rte_IWriteRef_Runnable_Logic_Swc_Input_P_Swc_Input_status_value();

  */
} /* FUNC(void, RTE_CODE) Swc_Input_Runnable_Logic_Swc_Input (void) */

FUNC(void, RTE_CODE) Swc_Input_Init (void)
{
  ComM_ModeType arg_Call_ComMode = FULL_COMMUNICATION;
  Std_ReturnType ret_Call;

  ret_Call = Rte_Call_UR_ComMUser_0_RequestComMode(arg_Call_ComMode);

} /* FUNC(void, RTE_CODE) Swc_Input_Init (void) */

FUNC(void, RTE_CODE) Swc_Input_Shutdown (void)
{

} /* FUNC(void, RTE_CODE) Swc_Input_Shutdown (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
