/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.3.10
 * on Wed Jan 11 13:52:37 CET 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Swc_Function.h>
#include "Dio.h"
#include "Pwm.h" 

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) Swc_Function_Runnable_Logic_Swc_Function (void)
{
  uint8 arg_IWrite_data = 0U;
  P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef;
  boolean ret_IRead;
  boolean ret_IRead_0;
  boolean ret_IRead_1;
  boolean ret_IRead_2;
  boolean arg_Call_value_R = 0U;
  boolean arg_Call_value_G = 0U;
  boolean arg_Call_value_B = 0U;
  boolean arg_Call_value_Extra = 0U;
  Std_ReturnType ret_Call;

  Rte_IWrite_Runnable_Logic_Swc_Function_P_Swc_Function_status_value(arg_IWrite_data);
  ret_IWriteRef = Rte_IWriteRef_Runnable_Logic_Swc_Function_P_Swc_Function_status_value();
  ret_IRead = Rte_IRead_Runnable_Logic_Swc_Function_R_Button_sw2_value();
  ret_IRead_0 = Rte_IRead_Runnable_Logic_Swc_Function_R_Button_sw3_value();
  ret_IRead_1 = Rte_IRead_Runnable_Logic_Swc_Function_R_Button_sw7_value();
  ret_IRead_2 = Rte_IRead_Runnable_Logic_Swc_Function_R_Button_sw8_value();
  

	//if (Dio_ReadChannel(DioConf_DioChannel_BTN_sw3) == STD_HIGH)
		
	if (ret_IRead == 1)
	{
		arg_Call_value_R = 1; 
		arg_Call_value_B = 1; 
	}
  
  else
  {
		arg_Call_value_R = 0; 
		arg_Call_value_B = 0; 
  }
  
  ret_Call = Rte_Call_R_Led_status_OP_Set_Led(arg_Call_value_R, arg_Call_value_G, arg_Call_value_B, arg_Call_value_Extra);
	
} /* FUNC(void, RTE_CODE) Swc_Function_Runnable_Logic_Swc_Function (void) */

FUNC(void, RTE_CODE) Swc_Function_Init (void)
{
  ComM_ModeType arg_Call_ComMode = FULL_COMMUNICATION;
  Std_ReturnType ret_Call;

  ret_Call = Rte_Call_UR_ComMUser_0_RequestComMode(arg_Call_ComMode);

} /* FUNC(void, RTE_CODE) Swc_Function_Init (void) */

FUNC(void, RTE_CODE) Swc_Function_Shutdown (void)
{

} /* FUNC(void, RTE_CODE) Swc_Function_Shutdown (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
