/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.3.10
 * on Wed Jan 11 13:52:37 CET 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Swc_IO_Hardware_Led.h>
#include "Dio.h"
#include "Pwm.h"
/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) Swc_IO_Hardware_Led_Runnable_Service_led_status (boolean value_R, boolean value_G, boolean value_B, boolean value_Extra)
{
  boolean ret_IrvIRead;
  uint8 arg_IrvIWrite_data = 0U;
  
  //USER DEFINED
  uint8 result = 0U;

  ret_IrvIRead = Rte_IrvIRead_Runnable_Service_led_status_IntRunVar_enable_led();
  Rte_IrvIWrite_Runnable_Service_led_status_IntRunVar_Leds_state(arg_IrvIWrite_data);
  /* suppress compiler warnings about unused arguments */
  (void)value_R;
  (void)value_G;
  (void)value_B;
  (void)value_Extra;
  
  // This turns the LED purple :3
  result = value_R | value_G | value_B; 
	if (result)
	{
		Pwm_SetDutyCycle(PwmChannel_2_BLUE, 0x1000);  
		Pwm_SetDutyCycle(PwmChannel_0_RED, 0x1000);  
	}
	
	else
	{
		Pwm_SetDutyCycle(PwmChannel_2_BLUE, 0x0000);  
		Pwm_SetDutyCycle(PwmChannel_0_RED, 0x0000); 
	}

} /* FUNC(void, RTE_CODE) Swc_IO_Hardware_Led_Runnable_Service_led_status (boolean value_R, boolean value_G, boolean value_B, boolean value_Extra) */

FUNC(void, RTE_CODE) Swc_IO_Hardware_Led_Runnable_Logic_enable_led (void)
{
  boolean ret_IrvIRead;
  boolean arg_IrvIWrite_data = 0U;
  boolean ret_IRead;

  ret_IrvIRead = Rte_IrvIRead_Runnable_Logic_enable_led_IntRunVar_enable_led();
  Rte_IrvIWrite_Runnable_Logic_enable_led_IntRunVar_enable_led(arg_IrvIWrite_data);
  ret_IRead = Rte_IRead_Runnable_Logic_enable_led_R_enable_led_value();

} /* FUNC(void, RTE_CODE) Swc_IO_Hardware_Led_Runnable_Logic_enable_led (void) */

FUNC(void, RTE_CODE) Swc_IO_Hardware_Led_Runnable_10ms (void)
{
  uint8 ret_IrvIRead;

  ret_IrvIRead = Rte_IrvIRead_Runnable_10ms_IntRunVar_Leds_state();



} /* FUNC(void, RTE_CODE) Swc_IO_Hardware_Led_Runnable_10ms (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
