/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.3.10
 * on Fri Jan 13 12:44:23 CET 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_Swc_IO_Hardware_Button.h>
#include "Dio.h"
/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(void, RTE_CODE) Swc_IO_Hardware_Button_Runnable_Logic_Swc_IO_Hardware_Button (void)
{
  boolean arg_IWrite_data = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef;
  boolean arg_IWrite_data_0 = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_0;
  boolean arg_IWrite_data_1 = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_1;
  boolean arg_IWrite_data_2 = 0U;
  P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) ret_IWriteRef_2;
  
  
  //Sends the signal that one of these buttons is pressed
  if (Dio_ReadChannel(DioConf_DioChannel_BTN_sw2) == STD_HIGH)
	{
		arg_IWrite_data = 1;
	}
	else {
		arg_IWrite_data = 0;
	}

  if (Dio_ReadChannel(DioConf_DioChannel_BTN_sw3) == STD_HIGH)
	{
		arg_IWrite_data_0 = 1;
	}
	else {
		arg_IWrite_data_0 = 0;
	}
	
	if (Dio_ReadChannel(DioConf_DioChannel_BTN_sw7) == STD_HIGH)
	{
		arg_IWrite_data_1 = 1;
	}
	else {
		arg_IWrite_data_1 = 0;
	}
	
	if (Dio_ReadChannel(DioConf_DioChannel_BTN_sw8) == STD_HIGH)
	{
		arg_IWrite_data_2 = 1;
	}
	else {
		arg_IWrite_data_2 = 0;
	}
	
  Rte_IWrite_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw2_value(arg_IWrite_data);
  ret_IWriteRef = Rte_IWriteRef_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw2_value();
  
  Rte_IWrite_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw3_value(arg_IWrite_data_0);
  ret_IWriteRef_0 = Rte_IWriteRef_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw3_value();
  
  Rte_IWrite_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw7_value(arg_IWrite_data_1);
  ret_IWriteRef_1 = Rte_IWriteRef_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw7_value();
  
  Rte_IWrite_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw8_value(arg_IWrite_data_2);
  ret_IWriteRef_2 = Rte_IWriteRef_Runnable_Logic_Swc_IO_Hardware_Button_P_IO_Button_sw8_value();

} /* FUNC(void, RTE_CODE) Swc_IO_Hardware_Button_Runnable_Logic_Swc_IO_Hardware_Button (void) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
